Various additions for 0.5.0
VoxelForge/VoxelForge pull request #134
Opened 2024-08-30 00:17 UTC by DragonWrangler1

2024-08-30 15:05 UTC, crispiebacon requested changes
I'll leave it at 24 cases for now. 1k files is a lot to review.

2024-08-30 15:05 UTC, crispiebacon commented on mods/HELP/vlf_doc_basics/README.md
also wrong naming.

2024-08-30 15:05 UTC, crispiebacon commented on mods/HELP/vlf_doc_basics/basics.lua
entity effect issue again.

2024-08-30 15:05 UTC, crispiebacon commented on mods/HUD/vlf_inventory/API.md
vlf ?

2024-08-30 15:05 UTC, crispiebacon commented on mods/HUD/vlf_inventory/README.txt
same as above.

2024-08-31 01:42 UTC, closed without merging

2024-08-31 01:42 UTC, DragonWrangler1 commented
This clearly needs more testing.