WIP: Next attempt at 24w35a
VoxelForge/VoxelForge pull request #135
Opened 2024-08-31 04:00 UTC by DragonWrangler1

2024-08-31 16:36 UTC, DragonWrangler1 commented
I actually think I won't use MCLA's new effects api, However I will cherrypick a commit.

2024-09-03 17:48 UTC, crispiebacon requested changes

2024-09-03 17:49 UTC, crispiebacon commented
It's much better than the other pr. And this time I reviewed all files... I do have one small question. How come there are some many files that it says are empty ?

2024-09-03 18:14 UTC, DragonWrangler1 commented
> It's much better than the other pr. And this time I reviewed all files.

I tried to fix all the things, next time I'll be more careful when using sed. I didn't think about the fact that I was in the main VoxelForge directory and not the EFFECTS directory.

> I do have one small question. How come there are some many files that it says are empty ?

Probably because I had updated them initially.

2024-09-03 18:23 UTC, crispiebacon approved these changes
Other than that one nitpick, Approving.

2024-09-03 18:23 UTC, crispiebacon commented on mods/CORE/vlf_textures/textures/PP/block/vlf_potions_effect_dolphin_grace.png
These aren't supposed to be here correct ?

2024-09-03 18:25 UTC, DragonWrangler1 commented
@crispiebacon : Removed the textures.

2024-09-03 22:24 UTC, crispiebacon commented
I can't seem to find any bugs.

2024-09-03 22:25 UTC, merged